<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Playlist extends Model {
    //
    protected $guarded = [];

    public function videos() {
		return $this->hasMany( 'App\Video', 'playlist_id', 'id' );
	}

    protected static function boot() {
        parent::boot(); // TODO: Change the autogenerated stub
//        static::creating( function ( $playlist ) {
//            $playlist->user_id = auth()->user()->id;
//        } );
    }
}
