<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Playlist extends Model {
    //
    protected $guarded = [];

    protected static function boot() {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating( function ( $playlist ) {
            $playlist->user_id = auth()->id();
        } );
    }
}
