<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Playlist extends Model
{
    //
    protected $guarded = [];
//    protected static function boot() {
//        parent::boot(); // TODO: Change the autogenerated stub
//        static::saving(function ($video) {
//            $video->setAttribute('user_id', auth()->id());
//        });
//    }
}
